version: '3'
services:
  os_info_dump:
    build:
      context: ./
    restart: unless-stopped
    volumes:
      - "./build/:/build"
      - ".:/workspace"
    working_dir: /workspace
    entrypoint: ["/bin/bash"]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
